package org.collcal.collcal.presentation.ui.theme

object Strings {
    const val appName = "COLLCAL"
    const val appDescription = "Visualize your college life"
    const val signIn = "로그인"
    const val signUp = "회원가입"
    const val id = "아이디"
    const val password = "비밀번호"
    const val idEn = "ID"
    const val passwordEn = "password"
    const val phoneNumber = "핸드폰 번호"
    const val phoneNumberPlaceholder = "010-1234-5678"
    const val email = "E-mail"
    const val emailPlaceholder = "collcal@callcal.com"
    const val checkRedundancy = "중복 확인"
    const val admissionYear = "입학 연도"
    const val admissionYearPlaceholder = "연도 선택 (학번)"
    const val school = "학교"
    const val schoolPlaceholder = "학교 이름을 선택하세요"
    const val department = "학과 선택"
    const val departmentPlaceholder = "확과 이름을 선택하세요"
    const val semester = "현재 학년/학기"
    const val semesterPlaceholder = "현재 상태를 선택하세요"
    const val home = "홈"
    const val todos = "할 일"
    const val user = "마이페이지"
    const val earnedCredits = "취득학점"
    const val averageCredit = "평점 평군"
    const val tasks = "Tasks"
    const val Add = "Add"
    const val next = "다음"
    const val taskContentPlaceholder = "추후 포트폴리오에 활용할 활동 내용을 기입하세요(활동 내용, 기여도, 성장 과정, 성과물 등)"
    const val save = "저장하기"
    const val todo = "To Do"
    const val scheduled = "Scheduled"
    const val completed = "Completed"
    const val moveToTodo = "ToDo로 이동"
    const val delete = "삭제하기"
    const val taskTilte = "활동명 입력"
    const val taskInfo = "(추가 정보 입력)"
    const val modify = "수정하기"
    const val add = "추가"
    const val course = "과목명"
    const val credit = "학점"
    const val grade = "성적"
}