package org.collcal.collcal.presentation.ui.theme

object Strings {
    const val appName = "COLLCAL"
    const val appDescription = ": design your college life"
    const val signIn = "로그인"
    const val signUp = "회원가입"
    const val id = "ID"
    const val password = "PASSWORD"
    const val phoneNumber = "PHONE NUMBER"
    const val email = "EMAIL"
    const val checkRedundancy = "중복 확인"
    const val admissionYear = "입학 연도"
    const val admissionYearPlaceholder = "입학 연도를 선택해주세요."
    const val school = "학교"
    const val schoolPlaceholder = "학교를 선택해주세요."
    const val department = "학과 선택"
    const val departmentPlaceholder = "확과를 선택해주세요."
    const val semester = "현재 학년/학기"
    const val semesterPlaceholder = "현재 학년/학기를 선택해주세요."
    const val earnedCredits = "취득학점"
    const val averageCredit = "평점 평군"
    const val tasks = "Tasks"
    const val Add = "Add"
    const val next = "다음"
    const val taskContentPlaceholder = "추후 포트폴리오에 활용할 활동 내용을 기입하세요(활동 내용, 기여도, 성장 과정, 성과물 등)"
    const val save = "저장하기"
    const val todo = "To Do"
    const val scheduled = "Scheduled"
    const val completed = "Completed"
    const val moveToTodo = "ToDo로 옮기기"
    const val delete = "삭제하기"
    const val taskTilte = "활동명 입력"
    const val taskInfo = "(추가 정보 입력)"
    const val modify = "수정하기"
    const val add = "추가"
    const val course = "과목명"
    const val credit = "학점"
    const val grade = "성적"
}